### PR TITLE
Updated ImageNet results on ResNet50.

### PR DESCRIPTION
**Pull request by aryabhata-archive**

### CODE REVIEW

**Comment by tgilewicz** [comment]
Thanks for your contribution! 
I see that you have obtained 77.80 TOP1 accuracy on ResNet50 and ImageNet. Is this average form many experiments? My results are: 0.7789, 0.7792, 0.7792.

**Comment by tgilewicz** [comment]
I see that you have obtained 77.80 TOP1 accuracy on ResNet50 and ImageNet. Is that the average of many experiments? My results are: 0.7789, 0.7792, 0.7792.

**Comment by aryabhata-archive** [comment]
It is an average, My experiment results are 77.79, 77.80, 77.82.

**Comment by tgilewicz** [comment]
Thanks for your contribution! Did you change any hyperparameters? The results are very close but not equal.

**Comment by aryabhata-archive** [comment]
I didn't change any parameters. Just re-run the code with ImageNet data. And yes, I noticed that your results are slightly higher. I think it is ok!

**Pull request merged**
